# Adding Layers

In [1]:
inputs = [1 2 3 2.5;
        2. 5. -1. 2; 
        -1.5 2.7 3.3 -0.8]
weights = [0.2 0.8 -0.5 1;
        0.5 -0.91 0.26 -0.5;
        -0.26 -0.27 0.17 0.87]
biases = [2, 3, 0.5]
weights2 = [0.1 -0.14 0.5;
        -0.5 0.12 -0.33;
        -0.44 0.73 -0.13]
biases2 = [-1, 2, -0.5]

3-element Vector{Float64}:
 -1.0
  2.0
 -0.5

In [8]:
layer_outputs = inputs * weights' .+ biases'

3×3 Matrix{Float64}:
 4.8    1.21   2.385
 8.9   -1.81   0.2
 1.41   1.051  0.026

In [9]:
layer_outputs * weights2' .+ biases2'

3×3 Matrix{Float64}:
  0.5031   -1.04185  -2.03875
  0.2434   -2.7332   -5.7633
 -0.99314   1.41254  -0.35655

In [1]:
using PyCall
nnfs = pyimport("nnfs")
nnfs.init()
nnfs_datasets = pyimport("nnfs.datasets")
spiral_data = nnfs_datasets.spiral_data

PyObject <function create_data at 0x7fcf1ab51240>

In [2]:
X, y = spiral_data(samples=100, classes=3)

(Float32[0.0 0.0; 0.002995557 0.009646608; … ; -0.9793868 -0.14387996; -0.9427888 0.33339068], UInt8[0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00  …  0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02])

In [18]:
function Layer_Dense(n_inputs, n_neurons, inputs)
    weights = 0.01 * rand(Float64, (n_inputs, n_neurons))
    biases = zeros(Float64, 1, n_neurons)
    output = inputs * weights .+ biases
    return output
end

Layer_Dense

In [19]:
Layer_Dense(2,3,X)

300×3 Matrix{Float64}:
  0.0           0.0           0.0
  8.41237e-5    0.000119543   9.5126e-5
  0.00021234    0.000264311   0.000164412
  0.000311014   0.000308977   8.27482e-5
  0.000428043   0.0004389     0.00014151
  0.000298971   0.000493924   0.000477769
  0.000673504   0.000749498   0.000341798
  0.000726339   0.000920474   0.000595479
  0.00086679    0.00105866    0.000630131
  0.00100785    0.00111053    0.000489149
  0.00112244    0.00124872    0.000568873
  0.000850966   0.000668454  -0.000131428
  0.00113846    0.00105037    0.000139811
  ⋮                          
 -0.00987072   -0.0113781    -0.00580542
 -0.00943217   -0.00957275   -0.00291873
 -0.00876092   -0.0115638    -0.0081153
 -0.00961232   -0.0120158    -0.00754537
 -0.00427974   -0.00175641    0.00390774
 -0.00947342   -0.0121604    -0.00808004
 -0.0104833    -0.0114184    -0.00481927
 -0.00693798   -0.00518671    0.00160389
 -0.00974062   -0.00949289   -0.00221958
 -0.00768492   -0.00615666    0.000944258
 -0

In [9]:
size(X)

(300, 2)

In [10]:
typeof(X)

Matrix{Float32} (alias for Array{Float32, 2})

In [ ]:
function initialize(LayerDense, n_inputs, n_neurons)
    weights = 0.01 * rand(Float64, (n_inputs, n_neurons))
    biases = zeros(Float64, 1, n_neurons)
    return weights, biases
end

In [20]:
mutable struct LayerDense
    n_inputs
    n_neurons
    weights
    biases
    initialize
    forward
    output

    function LayerDense(n_inputs, n_neurons)
        this = new()

        this.n_inputs = n_inputs
        this.n_neurons = n_neurons
        
        this.initialize = function()
            this.weights = 0.01 * rand(Float64, (this.n_inputs, this.n_neurons))
            this.biases = zeros(Float64, 1, this.n_neurons)
        end

        this.forward = function(inputs)
            this.output = inputs * this.weights .+ this.biases
            return this.output
        end

        return this
    end
end

In [21]:
dense = LayerDense(2, 3)
dense.initialize()
dense.forward(X)

300×3 Matrix{Float64}:
  0.0           0.0           0.0
  9.80655e-5    4.26857e-5    7.10069e-5
  0.000220295   7.86892e-5    0.000139883
  0.000265797   5.45866e-5    0.000122724
  0.000375751   8.57297e-5    0.000183262
  0.000398779   0.000205322   0.000324969
  0.000634089   0.00018062    0.000350282
  0.000765456   0.000281867   0.000495686
  0.00088451    0.000305475   0.000549696
  0.000940839   0.000261715   0.000512567
  0.00105648    0.000300725   0.000583376
  0.000598505   1.20082e-5    0.000149782
  0.000914271   0.000137216   0.000364455
  ⋮                          
 -0.0095795    -0.00295269   -0.00554747
 -0.0082081    -0.00181252   -0.00393457
 -0.00956833   -0.00375783   -0.00646371
 -0.0100094    -0.00360156   -0.00638567
 -0.00184192    0.00118579    0.000934369
 -0.0100964    -0.00379659   -0.00662799
 -0.00968954   -0.00261914   -0.00519186
 -0.00468812    0.000106428  -0.000944461
 -0.00819064   -0.00156681   -0.0036502
 -0.00549228   -0.000201576  -0.00147877

In [7]:
mutable struct Layer_Dense
    weights
    biases
    output
end

function initialize(Layer_Dense, n_inputs, n_neurons)
    Layer_Dense.weights = 0.01 * rand(Float64, (n_inputs, n_neurons))
    Layer_Dense.biases = zeros(Float64, 1, n_neurons)
end

function forward(Layer_Dense, inputs)
    output = inputs * Layer_Dense.weights .+ Layer_Dense.biases
    return output
end

forward (generic function with 1 method)

In [8]:
dense = Layer_Dense(0,0,0)
initialize(dense, 2, 3)
forward(dense, X)

300×3 Matrix{Float64}:
  0.0           0.0           0.0
  2.33784e-5    4.27533e-5    7.77123e-6
  4.32891e-5    8.70801e-5    2.08036e-5
  3.05791e-5    8.40412e-5    3.29517e-5
  4.78225e-5    0.000123268   4.49173e-5
  0.000112097   0.000190392   2.54261e-5
  9.99888e-5    0.000226747   6.88053e-5
  0.000154948   0.000306976   7.06427e-5
  0.000168193   0.000344181   8.5566e-5
  0.000144989   0.000333166   0.000103313
  0.000166481   0.000377681   0.000114681
  9.3532e-6     0.000131457   9.57748e-5
  7.80647e-5    0.000262745   0.000123179
  ⋮                          
 -0.00163075   -0.00354226   -0.000995902
 -0.00101236   -0.00266136   -0.000992909
 -0.00206266   -0.0039594    -0.000837435
 -0.00198097   -0.00397025   -0.000940139
  0.000627236   0.000232482  -0.00053263
 -0.00208602   -0.00409005   -0.000916452
 -0.00145232   -0.00339151   -0.00107883
  3.43008e-5   -0.000925256  -0.000789213
 -0.000880446  -0.00252969   -0.00103785
 -0.000134858  -0.00125395   -0.000861117
 -

In [1]:
using PyCall
nnfs = pyimport("nnfs")
nnfs.init()
nnfs_datasets = pyimport("nnfs.datasets")
spiral_data = nnfs_datasets.spiral_data

PyObject <function create_data at 0x7f719fb01240>

In [2]:
X, y = spiral_data(samples=100, classes=3)

(Float32[0.0 0.0; 0.002995557 0.009646608; … ; -0.9793868 -0.14387996; -0.9427888 0.33339068], UInt8[0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00  …  0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02])

In [3]:
n_inputs = 2
n_neurons = 3

3

In [4]:
random_number = rand(Float64, (n_inputs, n_neurons))

2×3 Matrix{Float64}:
 0.348539  0.485843  0.366239
 0.853947  0.377604  0.233105

In [11]:
mutable struct LayerDense
    # these will change under training and used in forward inference
    weights
    biases     # constructor method; no need to define setter: LayerDense(weights::Array{Float64, 2}, biases::Vector{Float64})
    function LayerDense(n_inputs::Int64, n_neurons::Int64; random=true)
        new(
            # weights
            random ? 0.01 * rand(Float64, (n_inputs, n_neurons)) : zeros(Float64, n_neurons, n_inputs),
            # biases
            zeros(Float64, n_neurons)
        )
    end
end # multiple dispatch pattern for the "method"
function forward(ld::LayerDense, inputs::Vector{Float64})::Vector{Float64}
    return ld.weights * inputs + ld.biases
end

forward (generic function with 1 method)

In [5]:
function Layer_Dense(n_inputs, n_neurons, inputs)
    weights = 0.01 * random_number
    biases = zeros(Float64, 1, n_neurons)
    output = inputs * weights .+ biases
    return output
end

Layer_Dense (generic function with 1 method)

In [6]:
Layer_Dense(2,3,X)

300×3 Matrix{Float64}:
  0.0           0.0           0.0
  8.32332e-5    1.10425e-5    7.81023e-5
  0.000166291   2.28306e-5    0.000178112
  0.000152107   2.29116e-5    0.000221147
  0.000225327   3.33729e-5    0.000311305
  0.000376637   4.85494e-5    0.000312687
  0.000423476   6.04462e-5    0.000519771
  0.000587966   8.02993e-5    0.000617575
  0.000655085   9.0465e-5     0.000716761
  0.000620784   8.89664e-5    0.000772191
  0.000705314   0.000100687   0.000866046
  0.00020913    3.88538e-5    0.00051513
  0.00046242    7.30047e-5    0.00076851
  ⋮                          
 -0.00666701   -0.000938913  -0.00781777
 -0.00484975   -0.000722101  -0.00680963
 -0.00763163   -0.00103068   -0.00768351
 -0.00758718   -0.00104035   -0.0080887
  0.000826853   2.08535e-5   -0.00177458
 -0.00785      -0.00106819   -0.00813362
 -0.00630168   -0.000907496  -0.00796446
 -0.00139702   -0.000281319  -0.00406607
 -0.00454858   -0.000692789  -0.00683258
 -0.00202901   -0.000367043  -0.00471304
 -0

In [6]:
dense = LayerDenseV(2,3)

LoadError: UndefVarError: LayerDense not defined

In [5]:
dense.weights

2×3 Matrix{Float64}:
 0.00724326  0.00235903  0.00540998
 0.00435688  0.00181897  0.00711043

In [6]:
dense.biases

3-element Vector{Float64}:
 0.0
 0.0
 0.0

In [7]:
forward(dense, X)

300×3 Matrix{Float64}:
  0.0           0.0           0.0
  6.37267e-5    2.46135e-5    8.47974e-5
  0.000161106   5.86949e-5    0.000180344
  0.000236495   7.88023e-5    0.000193791
  0.000325393   0.000109707   0.000279008
  0.000226018   9.38101e-5    0.000363548
  0.000511594   0.000178021   0.000492037
  0.000550976   0.000202275   0.000631621
  0.000657784   0.000237738   0.000717926
  0.00076564    0.000265384   0.000726361
  0.00085261    0.000296651   0.000819677
  0.000648259   0.000199383   0.000370949
  0.000866227   0.000281059   0.000636774
  ⋮                          
 -0.00749517   -0.00264514   -0.00756555
 -0.00717086   -0.00240841   -0.00605928
 -0.00664264   -0.00248209   -0.00803366
 -0.00729268   -0.00266169   -0.00820964
 -0.00327102   -0.000855514  -0.000420382
 -0.00718517   -0.00265242   -0.00837754
 -0.00796474   -0.00274823   -0.00743571
 -0.00528707   -0.00160144   -0.00278741
 -0.007408     -0.00245113   -0.00590373
 -0.00585351   -0.0018116    -0.00345798

In [10]:
X * dense.weights .+ dense.biases'

300×3 Matrix{Float64}:
  0.0           0.0           0.0
  8.08152e-5    7.53484e-5    7.71744e-5
  0.000134934   0.000169604   0.000131231
  5.34463e-5    0.000205436   5.94821e-5
  9.87573e-5    0.00029025    0.000105062
  0.000414648   0.000305772   0.000391581
  0.000264072   0.000489091   0.000265355
  0.000491742   0.000589153   0.000476679
  0.0005134     0.000681187   0.00050126
  0.000374796   0.000725821   0.000378335
  0.000439403   0.0008149     0.000441596
 -0.000180191   0.000464784  -0.000137737
  4.68673e-5    0.000707645   8.07835e-5
  ⋮                          
 -0.0045964    -0.0073845    -0.00455749
 -0.00199417   -0.00634156   -0.00214755
 -0.00678218   -0.00735987   -0.00653287
 -0.00620194   -0.00770567   -0.0060269
  0.003868     -0.00145462    0.00341912
 -0.00669952   -0.00776936   -0.00648035
 -0.00365341   -0.00747662   -0.00370969
  0.00195474   -0.00364465    0.00157001
 -0.00133453   -0.00633286   -0.00155053
  0.00140593   -0.00426336    0.00104012
 -0.

In [7]:
mutable struct LayerDense2
    weights
    biases
    function LayerDense2(n_inputs::Int64, n_neurons::Int64)
        new(0.01 * random_number, zeros(Float64, 1, n_neurons))
    end
end
function forward2(LayerDense2, inputs)
    return inputs * LayerDense2.weights .+ LayerDense2.biases
end

forward2 (generic function with 1 method)

In [8]:
dense2 = LayerDense2(2,3)

LayerDense2([0.0039773970638304545 0.0006232131218292825 0.0064746778413247545; 0.007393135964187503 0.0009511787763520663 0.006085774141655438], [0.0 0.0 0.0])

In [9]:
forward2(dense2, X)

300×3 Matrix{Float64}:
  0.0           0.0           0.0
  8.32332e-5    1.10425e-5    7.81023e-5
  0.000166291   2.28306e-5    0.000178112
  0.000152107   2.29116e-5    0.000221147
  0.000225327   3.33729e-5    0.000311305
  0.000376637   4.85494e-5    0.000312687
  0.000423476   6.04462e-5    0.000519771
  0.000587966   8.02993e-5    0.000617575
  0.000655085   9.0465e-5     0.000716761
  0.000620784   8.89664e-5    0.000772191
  0.000705314   0.000100687   0.000866046
  0.00020913    3.88538e-5    0.00051513
  0.00046242    7.30047e-5    0.00076851
  ⋮                          
 -0.00666701   -0.000938913  -0.00781777
 -0.00484975   -0.000722101  -0.00680963
 -0.00763163   -0.00103068   -0.00768351
 -0.00758718   -0.00104035   -0.0080887
  0.000826853   2.08535e-5   -0.00177458
 -0.00785      -0.00106819   -0.00813362
 -0.00630168   -0.000907496  -0.00796446
 -0.00139702   -0.000281319  -0.00406607
 -0.00454858   -0.000692789  -0.00683258
 -0.00202901   -0.000367043  -0.00471304
 -0