In [1]:
layer_outputs = [4.8, 1.21, 2.385]

3-element Vector{Float64}:
 4.8
 1.21
 2.385

In [2]:
exp_values = Vector{Float64}()

Float64[]

In [3]:
E = exp(1.0)

2.718281828459045

In [4]:
for output in layer_outputs
    push!(exp_values, E ^ output)
end

In [5]:
exp_values

3-element Vector{Float64}:
 121.51041751873483
   3.353484652549023
  10.859062664920513

In [6]:
norm_base = sum(exp_values) # We sum all values
norm_values = []
for value in exp_values
    push!(norm_values, value / norm_base)
end

In [7]:
norm_values

3-element Vector{Any}:
 0.8952826639572619
 0.024708306782099374
 0.0800090292606387

In [8]:
sum(norm_values)

0.9999999999999999

In [9]:
exp_values = exp.(layer_outputs)

3-element Vector{Float64}:
 121.51041751873485
   3.3534846525490236
  10.859062664920515

In [10]:
norm_values = exp_values/ sum(exp_values)

3-element Vector{Float64}:
 0.8952826639572619
 0.02470830678209937
 0.0800090292606387

In [1]:
using PyCall
nnfs = pyimport("nnfs")
nnfs.init()
nnfs_datasets = pyimport("nnfs.datasets")
spiral_data = nnfs_datasets.spiral_data

PyObject <function create_data at 0x7ffb31f89240>

In [2]:
X, y = spiral_data(samples=100, classes=3)

(Float32[0.0 0.0; 0.002995557 0.009646608; … ; -0.9793868 -0.14387996; -0.9427888 0.33339068], UInt8[0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00  …  0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02])

In [3]:
mutable struct Layer_Dense
    weights::Matrix{Float64}
    biases::Matrix{Float64}
    function Layer_Dense(n_inputs::Int64, n_neurons::Int64)
        new(0.01 * rand(Float64, (n_inputs, n_neurons)), zeros(Float64, 1, n_neurons))
    end
end

function Layer_Dense_forward(layer_dense::Layer_Dense, inputs::Matrix{Float64})
    return inputs * layer_dense.weights .+ layer_dense.biases
end

Layer_Dense_forward (generic function with 1 method)

In [4]:
function Activation_Relu_forward(inputs::Matrix{Float64})
    return max.(0, inputs)
    #return maximum(inputs, dims=2)
end

Activation_Relu_forward (generic function with 1 method)

In [5]:
function Activation_Softmax_forward(inputs::Matrix{Float64})
    exp_values = exp.(inputs .- maximum(inputs, dims=2))
    
    return probabilities = exp_values ./ sum(exp_values, dims=2)
end

Activation_Softmax_forward (generic function with 1 method)

In [6]:
dense1 = Layer_Dense(2, 3)

Layer_Dense([0.005749258570919932 0.002662560631700419 0.008008369659216103; 0.00939479417643317 0.007257382713513387 0.0021909101266280396], [0.0 0.0 0.0])

In [15]:
dense1.weights

2×3 Matrix{Float64}:
 0.00574926  0.00266256  0.00800837
 0.00939479  0.00725738  0.00219091

In [18]:
dense1.weights = [-0.01306527  0.01658131 -0.00118164;
       -0.00680178  0.00666383 -0.0046072 ]

2×3 Matrix{Float64}:
 -0.0130653   0.0165813   -0.00118164
 -0.00680178  0.00666383  -0.0046072

In [7]:
size(dense1.biases)

(1, 3)

In [8]:
size(dense1.weights)

(2, 3)

In [9]:
dense2 = Layer_Dense(3, 3)

Layer_Dense([0.004182102707738766 0.002784672276187693 0.0076894473864766305; 0.0099513337164521 0.0027075113799880967 0.008081580590348289; 0.005606180407770341 0.0016458268498983387 0.007215120024938075], [0.0 0.0 0.0])

In [19]:
dense2.weights = [-0.01334258 -0.01346717  0.00693773;
       -0.00159573 -0.00133702  0.01077744;
       -0.01126826 -0.00730678 -0.0038488 ]

3×3 Matrix{Float64}:
 -0.0133426   -0.0134672    0.00693773
 -0.00159573  -0.00133702   0.0107774
 -0.0112683   -0.00730678  -0.0038488

In [20]:
dense1_output = Layer_Dense_forward(dense1, Float64.(X))

300×3 Matrix{Float64}:
  0.0           0.0           0.0
 -0.000104752   0.000113954  -4.79835e-5
 -0.000274148   0.000317292  -8.69218e-5
 -0.000421884   0.000526663  -5.59127e-5
 -0.000577077   0.000714014  -8.94304e-5
 -0.000354307   0.000350255  -0.000233635
 -0.00089267    0.00107679   -0.000194532
 -0.000933508   0.00107238   -0.000312274
 -0.00112438    0.00131128   -0.000336297
 -0.0013387     0.00162009   -0.000281018
 -0.0014878     0.00179484   -0.00032386
 -0.00120036    0.00158119    8.65948e-6
 -0.00156528    0.00199173   -0.000130997
  ⋮                          
  0.0129803    -0.0154693     0.00321064
  0.0127419    -0.0158119     0.00188052
  0.0111397    -0.0125693     0.00418793
  0.0123971    -0.0143231     0.00398122
  0.00645469   -0.00922423   -0.00151018
  0.0121351    -0.0138639     0.00421446
  0.0139591    -0.0169567     0.00280168
  0.00985511   -0.0131001    -0.000311079
  0.0132608    -0.0166402     0.00158308
  0.010809     -0.0141844     3.14037e-5
  0.

In [21]:
activation1_output = Activation_Relu_forward(dense1_output)

300×3 Matrix{Float64}:
 0.0         0.0          0.0
 0.0         0.000113954  0.0
 0.0         0.000317292  0.0
 0.0         0.000526663  0.0
 0.0         0.000714014  0.0
 0.0         0.000350255  0.0
 0.0         0.00107679   0.0
 0.0         0.00107238   0.0
 0.0         0.00131128   0.0
 0.0         0.00162009   0.0
 0.0         0.00179484   0.0
 0.0         0.00158119   8.65948e-6
 0.0         0.00199173   0.0
 ⋮                        
 0.0129803   0.0          0.00321064
 0.0127419   0.0          0.00188052
 0.0111397   0.0          0.00418793
 0.0123971   0.0          0.00398122
 0.00645469  0.0          0.0
 0.0121351   0.0          0.00421446
 0.0139591   0.0          0.00280168
 0.00985511  0.0          0.0
 0.0132608   0.0          0.00158308
 0.010809    0.0          3.14037e-5
 0.0137746   0.0          0.00182017
 0.0100501   0.0          0.0

In [26]:
dense2_output = Layer_Dense_forward(dense2, activation1_output)

300×3 Matrix{Float64}:
  0.0           0.0          0.0
 -1.81839e-7   -1.52358e-7   1.22813e-6
 -5.06312e-7   -4.24225e-7   3.41959e-6
 -8.40411e-7   -7.04158e-7   5.67608e-6
 -1.13937e-6   -9.54651e-7   7.69524e-6
 -5.58912e-7   -4.68298e-7   3.77485e-6
 -1.71826e-6   -1.43969e-6   1.1605e-5
 -1.71123e-6   -1.43379e-6   1.15575e-5
 -2.09245e-6   -1.75321e-6   1.41322e-5
 -2.58523e-6   -2.16609e-6   1.74604e-5
 -2.86408e-6   -2.39974e-6   1.93438e-5
 -2.62073e-6   -2.17736e-6   1.70079e-5
 -3.17827e-6   -2.66299e-6   2.14658e-5
  ⋮                          
 -0.00020937   -0.000198268  7.7697e-5
 -0.0001912    -0.000185338  8.11619e-5
 -0.000195823  -0.000180621  6.11658e-5
 -0.000210271  -0.000196044  7.06848e-5
 -8.61222e-5   -8.69264e-5   4.47809e-5
 -0.000209404  -0.00019422   6.79696e-5
 -0.00021782   -0.000208461  8.60613e-5
 -0.000131493  -0.00013272   6.83721e-5
 -0.000194772  -0.000190153  8.59069e-5
 -0.000144574  -0.000145796  7.48691e-5
 -0.000204299  -0.000198804  8.8559e

In [27]:
Activation_Softmax_forward(dense2_output)

300×3 Matrix{Float64}:
 0.333333  0.333333  0.333333
 0.333333  0.333333  0.333334
 0.333333  0.333333  0.333334
 0.333333  0.333333  0.333335
 0.333332  0.333332  0.333335
 0.333333  0.333333  0.333334
 0.333332  0.333332  0.333336
 0.333332  0.333332  0.333336
 0.333331  0.333332  0.333337
 0.333331  0.333331  0.333338
 0.333331  0.333331  0.333338
 0.333331  0.333331  0.333338
 0.333331  0.333331  0.333339
 ⋮                   
 0.3333    0.333304  0.333396
 0.333302  0.333304  0.333393
 0.333303  0.333308  0.333389
 0.333301  0.333305  0.333394
 0.333319  0.333319  0.333363
 0.333301  0.333306  0.333393
 0.333299  0.333302  0.3334
 0.333311  0.333311  0.333378
 0.333302  0.333303  0.333395
 0.333309  0.333309  0.333382
 0.3333    0.333302  0.333398
 0.333311  0.33331   0.333379

In [13]:
exponent = exp.(dense2_output .- maximum(dense2_output, dims=2))

300×3 Matrix{Float64}:
 1.0       1.0       1.0
 1.0       0.999999  1.0
 0.999999  0.999997  1.0
 0.999999  0.999997  1.0
 0.999999  0.999996  1.0
 0.999999  0.999995  1.0
 0.999998  0.999993  1.0
 0.999998  0.999991  1.0
 0.999997  0.999989  1.0
 0.999997  0.999989  1.0
 0.999996  0.999988  1.0
 0.999998  0.999994  1.0
 0.999997  0.99999   1.0
 ⋮                   
 1.0       1.0       1.0
 1.0       1.0       1.0
 1.0       1.0       1.0
 1.0       1.0       1.0
 1.0       0.999986  0.999999
 1.0       1.0       1.0
 1.0       1.0       1.0
 1.0       1.0       1.0
 1.0       1.0       1.0
 1.0       1.0       1.0
 1.0       1.0       1.0
 1.0       1.0       1.0

In [12]:
max.(0, dense1_output)

LoadError: UndefVarError: dense1_output not defined